import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Building2, CalendarDays, CheckCircle2, Clock3, Download, FileText, Filter, RotateCcw, Target, Trophy, UserRound, Users, XCircle } from 'lucide-react';
import { leadApi } from '../../api/leadManagementApi.js';
import { useAuthStore } from '../../store/authStore.js';

const card='rounded-[9px] border border-slate-200 bg-white';
const control='h-9 min-w-0 rounded-md border border-slate-200 bg-white px-2.5 text-[11px] font-semibold text-slate-700 outline-none focus:border-red-400 focus:ring-2 focus:ring-red-100';
const button='lead-button inline-flex h-9 items-center justify-center gap-1.5 whitespace-nowrap rounded-md border border-slate-200 bg-white px-3 text-[11px] font-bold text-slate-800 hover:bg-slate-50';
const primary=`${button} border-red-600 bg-red-600 text-white hover:bg-red-700`;
const money=(value)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(value||0));
const label=(value)=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
const week=()=>{const now=new Date(),day=(now.getDay()+6)%7,from=new Date(now);from.setDate(now.getDate()-day);const format=(date)=>date.toISOString().slice(0,10);return{from:format(from),to:format(now)};};
const categories=[['weekly-summary','Weekly Sales Meeting'],['sales-performance','Sales Performance'],['lead-analysis','Lead Analysis'],['staffing-delivery','Staffing & Delivery'],['skills-demand','Skills & Demand'],['pipeline-forecast','Pipeline & Forecast'],['company-market','Company & Market'],['activities','Activities & Productivity']];
const statuses=['NEW','CONTACTED','QUALIFIED','PROPOSAL','NEGOTIATION','WON','LOST','REJECTED','CONVERTED'];
const categoryKpis={
  'weekly-summary':['Total Leads','New Companies','Staffing Leads','Fixed Cost Leads','Won Leads','Lost Leads','Rejected Leads','Pipeline Value','Profiles Submitted','Interviews Scheduled','Candidates Selected','Candidates Joined','Proposal Sent','Open Leads','Win Rate','Avg Lead Age'],
  'sales-performance':['Total Leads','Won Leads','Lost Leads','Rejected Leads','Open Leads','Proposal Sent','Win Rate','Pipeline Value'],
  'lead-analysis':['Total Leads','Staffing Leads','Fixed Cost Leads','Won Leads','Lost Leads','Open Leads','Win Rate','Avg Lead Age'],
  'staffing-delivery':['Staffing Leads','Profiles Submitted','Interviews Scheduled','Candidates Selected','Candidates Joined','Open Leads','Won Leads','Avg Lead Age'],
  'skills-demand':['Total Leads','Staffing Leads','Fixed Cost Leads','Open Leads','Won Leads','Pipeline Value','Win Rate','Avg Lead Age'],
  'pipeline-forecast':['Pipeline Value','Open Leads','Proposal Sent','Won Leads','Lost Leads','Win Rate','Avg Lead Age','Total Leads'],
  'company-market':['New Companies','Total Leads','Staffing Leads','Fixed Cost Leads','Won Leads','Lost Leads','Pipeline Value','Win Rate'],
  activities:['Profiles Submitted','Interviews Scheduled','Candidates Selected','Candidates Joined','Proposal Sent','Open Leads','Won Leads','Avg Lead Age']
};

function useRequest(loader,dependency){const[state,setState]=useState({data:null,loading:true,error:''});useEffect(()=>{let active=true;setState(current=>({...current,loading:true,error:''}));loader().then(data=>active&&setState({data,loading:false,error:''})).catch(error=>active&&setState({data:null,loading:false,error:error.response?.data?.message||error.message||'Unable to load report.'}));return()=>{active=false};},[dependency]);return state;}
function Empty({message='No report data is available for the selected filters.'}){return <div className="grid min-h-36 place-items-center px-4 text-center text-xs font-semibold text-slate-400">{message}</div>}
function Select({value,onChange,children,ariaLabel}){return <select aria-label={ariaLabel} className={control} value={value||''} onChange={event=>onChange(event.target.value)}>{children}</select>}
function Kpi({title,value,previous,change,icon:Icon,tone='red'}){const positive=Number(change)>=0;const colors={red:'bg-red-50 text-red-600',blue:'bg-blue-50 text-blue-600',green:'bg-emerald-50 text-emerald-600',amber:'bg-amber-50 text-amber-600',slate:'bg-slate-100 text-slate-600'};return <section className={`${card} flex min-h-[76px] items-center gap-3 p-3`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-full ${colors[tone]}`}><Icon className="h-5 w-5"/></span><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-bold text-slate-600">{title}</p><p className="mt-0.5 text-[20px] font-black leading-none text-[#07152b]">{value}</p>{previous!==undefined&&<div className="mt-1.5 flex items-center justify-between gap-2 text-[9px]"><span className="text-slate-500">{previous}</span><b className={positive?'text-emerald-600':'text-red-600'}>{positive?'▲':'▼'} {Math.abs(Number(change||0)).toFixed(2)}%</b></div>}</div></section>}
function Chart({title,children}){return <section className={`${card} min-w-0 p-3`}><h2 className="text-[11px] font-extrabold text-[#07152b]">{title}</h2>{children}</section>}
function Bars({data=[],amount=false,horizontal=false}){const max=Math.max(1,...data.map(item=>Number(amount?item.amount:item.value)||0));if(!data.length)return <Empty/>;if(horizontal)return <div className="mt-3 space-y-2">{data.slice(0,10).map(item=>{const value=Number(amount?item.amount:item.value)||0;return <div className="grid grid-cols-[90px_1fr_auto] items-center gap-2 text-[9px]" key={item.label}><span className="truncate">{label(item.label)}</span><div className="h-2 rounded bg-slate-100"><i className="block h-full rounded bg-red-500" style={{width:`${Math.max(3,value/max*100)}%`}}/></div><b>{amount?money(value):value}</b></div>})}</div>;return <div className="mt-3 flex h-36 items-end gap-2 border-b border-slate-200 px-1">{data.slice(0,9).map(item=>{const value=Number(amount?item.amount:item.value)||0;return <div className="flex min-w-0 flex-1 flex-col items-center gap-1" key={item.label}><b className="text-[8px]">{amount?'':value}</b><i className="w-full max-w-8 rounded-t bg-red-500" style={{height:`${Math.max(5,value/max*96)}px`}}/><span className="w-full truncate text-center text-[8px] text-slate-500">{label(item.label)}</span></div>})}</div>}
function Donut({data=[]}){const palette=['#ef1f2c','#182235','#f59e0b','#64748b','#fb7185','#16a34a','#2563eb'];const total=data.reduce((sum,item)=>sum+Number(item.value||0),0);let cursor=0;const stops=data.map((item,index)=>{const start=cursor;cursor+=total?Number(item.value)*360/total:0;return`${palette[index%palette.length]} ${start}deg ${cursor}deg`});if(!data.length)return <Empty/>;return <div className="flex min-h-36 items-center justify-center gap-4"><div className="grid h-24 w-24 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(${stops.join(',')})`}}><div className="grid h-14 w-14 place-items-center rounded-full bg-white text-center"><b className="text-base">{total}</b></div></div><div className="space-y-1.5">{data.slice(0,7).map((item,index)=><div className="flex items-center gap-2 text-[8px]" key={item.label}><i className="h-2 w-2 rounded-full" style={{background:palette[index%palette.length]}}/><span className="max-w-24 truncate">{label(item.label)}</span><b>{item.value}</b></div>)}</div></div>}
function Funnel({data=[]}){if(!data.length)return <Empty/>;return <div className="mx-auto mt-3 max-w-56 space-y-0.5">{data.slice(0,7).map((item,index)=><div className="mx-auto flex h-5 items-center justify-center bg-red-500 text-[8px] font-bold text-white" style={{width:`${Math.max(36,100-index*10)}%`,opacity:1-index*.09}} key={item.label}>{label(item.label)} ({item.value})</div>)}</div>}
function MiniTable({title,columns,rows=[]}){return <section className={`${card} min-w-0 overflow-hidden`}><div className="flex items-center justify-between px-3 py-2"><h2 className="text-[10px] font-extrabold">{title}</h2><button className="text-[9px] font-bold text-red-600">View All</button></div><div className="overflow-x-auto"><table className="w-full min-w-[360px] text-left text-[8px]"><thead className="bg-slate-50 text-slate-500"><tr>{columns.map(column=><th className="px-3 py-2" key={column[0]}>{column[0]}</th>)}</tr></thead><tbody>{rows.slice(0,5).map((row,index)=><tr className="border-t border-slate-100" key={row.id||index}>{columns.map(column=><td className="max-w-36 truncate px-3 py-2" key={column[1]}>{column[2]?column[2](row[column[1]],row):row[column[1]]??'—'}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</div></section>}

export function LeadReportsPage(){
  const user=useAuthStore(state=>state.user);
  const initial=useMemo(()=>({...week(),employee:user?.role==='admin'?'':String(user?.id||'')}),[user?.id,user?.role]),[draft,setDraft]=useState(initial),[filters,setFilters]=useState(initial),[category,setCategory]=useState('weekly-summary'),[advanced,setAdvanced]=useState(false);
  const optionsRequest=useRequest(leadApi.options,'options'),report=useRequest(()=>leadApi.report(category,filters),`${category}:${JSON.stringify(filters)}`),options=optionsRequest.data||{},data=report.data||{},changes=data.changes||{};
  const update=(key,value)=>setDraft(current=>({...current,[key]:value}));const reset=()=>{const value={...week(),employee:user?.role==='admin'?'':String(user?.id||'')};setDraft(value);setFilters(value);setAdvanced(false)};
  const allKpis=[
    ['Total Leads',data.totalLeads,data.previousTotalLeads,changes.totalLeads,Users,'red'],['New Companies',data.newCompanies,data.previousNewCompanies,changes.newCompanies,Building2,'red'],['Staffing Leads',data.staffingLeads,data.previousStaffingLeads,changes.staffingLeads,Users,'red'],['Fixed Cost Leads',data.fixedCostLeads,data.previousFixedCostLeads,changes.fixedCostLeads,Building2,'red'],['Won Leads',data.wonLeads,data.previousWonLeads,changes.wonLeads,Trophy,'green'],['Lost Leads',data.lostLeads,data.previousLostLeads,changes.lostLeads,XCircle,'red'],['Rejected Leads',data.rejectedLeads,data.previousRejectedLeads,changes.rejectedLeads,XCircle,'red'],['Pipeline Value',money(data.pipelineValue),money(data.previousPipelineValue),changes.pipelineValue,Target,'amber'],
    ['Profiles Submitted',data.profilesSubmitted,undefined,0,FileText,'slate'],['Interviews Scheduled',data.interviewsScheduled,undefined,0,CalendarDays,'slate'],['Candidates Selected',data.candidatesSelected,undefined,0,UserRound,'green'],['Candidates Joined',data.candidatesJoined,undefined,0,CheckCircle2,'amber'],['Proposal Sent',data.proposalSent,data.previousProposalSent,changes.proposalSent,FileText,'slate'],['Open Leads',data.openLeads,data.previousOpenLeads,changes.openLeads,Clock3,'red'],['Win Rate',`${Number(data.winRate||0).toFixed(2)}%`,undefined,0,Target,'red'],['Avg Lead Age',`${Math.round(Number(data.averageLeadAge||0))} Days`,undefined,0,Clock3,'slate']
  ];
  const kpiByName=Object.fromEntries(allKpis.map(item=>[item[0],item]));
  const kpis=(categoryKpis[category]||categoryKpis['weekly-summary']).map(title=>kpiByName[title]).filter(Boolean);
  const reportSections={
    'weekly-summary':[
      <Chart key="employee" title="Lead Generation by Employee"><Bars data={data.byEmployee}/></Chart>,<Chart key="status" title="Lead Status Funnel"><Funnel data={data.byStatus}/></Chart>,<Chart key="type" title="Staffing vs Fixed Cost"><Donut data={data.byType}/></Chart>,<Chart key="skill" title="Skill-wise Lead Distribution (Top 10)"><Bars data={data.bySkill} horizontal/></Chart>,<Chart key="source" title="Lead Source Distribution"><Donut data={data.bySource}/></Chart>,
      <Chart key="period" title="Current Period Lead Trend"><Bars data={data.trend}/></Chart>,<Chart key="mode" title="Remote vs Onsite vs Hybrid"><Donut data={data.byWorkMode}/></Chart>,<Chart key="delivery" title="Delivery Funnel"><Funnel data={[{label:'Profiles Submitted',value:data.profilesSubmitted||0},{label:'Interviews',value:data.interviewsScheduled||0},{label:'Selected',value:data.candidatesSelected||0},{label:'Joined',value:data.candidatesJoined||0}]}/></Chart>,<Chart key="stage" title="Pipeline Value by Stage"><Bars data={data.byStageValue} amount horizontal/></Chart>,<Chart key="daily" title="Lead Trend by Day"><Bars data={data.trend}/></Chart>
    ],
    'sales-performance':[<Chart key="employee" title="Employee Sales Performance"><Bars data={data.byEmployee}/></Chart>,<Chart key="status" title="Win / Loss Funnel"><Funnel data={data.byStatus}/></Chart>,<Chart key="source" title="Source Performance"><Donut data={data.bySource}/></Chart>,<Chart key="stage" title="Pipeline Value by Stage"><Bars data={data.byStageValue} amount horizontal/></Chart>],
    'lead-analysis':[<Chart key="status" title="Leads by Status"><Donut data={data.byStatus}/></Chart>,<Chart key="type" title="Leads by Type"><Donut data={data.byType}/></Chart>,<Chart key="source" title="Leads by Source"><Bars data={data.bySource}/></Chart>,<Chart key="trend" title="Lead Creation Trend"><Bars data={data.trend}/></Chart>],
    'staffing-delivery':[<Chart key="delivery" title="Staffing Delivery Funnel"><Funnel data={[{label:'Profiles Submitted',value:data.profilesSubmitted||0},{label:'Interviews Scheduled',value:data.interviewsScheduled||0},{label:'Candidates Selected',value:data.candidatesSelected||0},{label:'Candidates Joined',value:data.candidatesJoined||0}]}/></Chart>,<Chart key="skills" title="Staffing Skills in Demand"><Bars data={data.bySkill} horizontal/></Chart>,<Chart key="mode" title="Work Mode Distribution"><Donut data={data.byWorkMode}/></Chart>,<Chart key="employee" title="Staffing Leads by Employee"><Bars data={data.byEmployee}/></Chart>],
    'skills-demand':[<Chart key="skills" title="Skill-wise Lead Distribution"><Bars data={data.bySkill} horizontal/></Chart>,<Chart key="type" title="Demand by Lead Type"><Donut data={data.byType}/></Chart>,<Chart key="mode" title="Remote / Onsite / Hybrid Demand"><Donut data={data.byWorkMode}/></Chart>,<Chart key="trend" title="Demand Trend"><Bars data={data.trend}/></Chart>],
    'pipeline-forecast':[<Chart key="stage" title="Pipeline Value by Stage"><Bars data={data.byStageValue} amount horizontal/></Chart>,<Chart key="funnel" title="Pipeline Stage Funnel"><Funnel data={data.byStatus}/></Chart>,<Chart key="employee" title="Pipeline by Owner"><Bars data={data.byEmployee} amount/></Chart>,<Chart key="trend" title="Pipeline Lead Trend"><Bars data={data.trend}/></Chart>],
    'company-market':[<Chart key="source" title="Market Source Distribution"><Donut data={data.bySource}/></Chart>,<Chart key="type" title="Company Demand by Lead Type"><Donut data={data.byType}/></Chart>,<Chart key="company" title="Company Acquisition Trend"><Bars data={data.trend}/></Chart>,<Chart key="skill" title="Skills Requested by Companies"><Bars data={data.bySkill} horizontal/></Chart>],
    activities:[<Chart key="delivery" title="Activity Conversion Funnel"><Funnel data={[{label:'Profiles Submitted',value:data.profilesSubmitted||0},{label:'Interviews Scheduled',value:data.interviewsScheduled||0},{label:'Candidates Selected',value:data.candidatesSelected||0},{label:'Candidates Joined',value:data.candidatesJoined||0}]}/></Chart>,<Chart key="employee" title="Activities by Employee"><Bars data={data.byEmployee}/></Chart>,<Chart key="status" title="Lead Status after Activities"><Donut data={data.byStatus}/></Chart>,<Chart key="trend" title="Productivity Trend"><Bars data={data.trend}/></Chart>]
  };
  const visibleSections=reportSections[category]||reportSections['weekly-summary'];
  return <div className="lead-module space-y-3 text-[#07152b]">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-[20px] font-black">Lead Reports</h1><p className="mt-1 text-[11px] text-slate-500">Lead Management <span className="px-2">›</span> Reports <span className="px-2">›</span><b className="text-red-600">{categories.find(item=>item[0]===category)?.[1]}</b></p></div><div className="flex gap-2"><a className={button} href={leadApi.reportExportUrl(category,filters)}><Download className="h-4 w-4"/>Export <span>⌄</span></a><button className={button}><CalendarDays className="h-4 w-4"/>Schedule Report <span>⌄</span></button></div></header>
    <section className={`${card} lead-report-filter-scroll p-2.5`}><div className="lead-report-filter-grid">
      <div className="flex h-9 items-center gap-1 rounded-md border border-slate-200 px-2"><CalendarDays className="h-3.5 w-3.5 shrink-0 text-slate-500"/><input className="h-8 min-w-0 flex-1 text-[10px] outline-none" type="date" value={draft.from} onChange={event=>update('from',event.target.value)}/><span className="text-[10px]">–</span><input className="h-8 min-w-0 flex-1 text-[10px] outline-none" type="date" value={draft.to} onChange={event=>update('to',event.target.value)}/></div>
      <Select ariaLabel="Compare with" value={draft.compare} onChange={value=>update('compare',value)}><option value="">Compare With</option><option value="previous">Previous Period</option></Select>
      <select aria-label="Employee" className={control} value={draft.employee||''} disabled={user?.role!=='admin'&&(options.reportEmployees||[]).length<=1} onChange={event=>update('employee',event.target.value)}>{user?.role==='admin'&&<option value="">Employee: All</option>}{(options.reportEmployees||[]).map(employee=><option key={employee.userId} value={employee.value}>{employee.name}</option>)}</select>
      <Select ariaLabel="Pipeline" value={draft.pipelineId} onChange={value=>update('pipelineId',value)}><option value="">Pipeline: All</option>{(options.pipelines||[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</Select>
      <Select ariaLabel="Lead type" value={draft.leadType} onChange={value=>update('leadType',value)}><option value="">Lead Type: All</option><option value="STAFFING">Staffing</option><option value="FIXED_COST">Fixed Cost</option></Select>
      <Select ariaLabel="Lead status" value={draft.status} onChange={value=>update('status',value)}><option value="">Lead Status: All</option>{statuses.map(item=><option key={item}>{label(item)}</option>)}</Select>
      <button className={button} onClick={()=>setAdvanced(value=>!value)}><Filter className="h-4 w-4"/>More Filters</button><button className={primary} onClick={()=>setFilters({...draft})}>Apply Filter</button>
    </div>{advanced&&<div className="mt-3 grid gap-2 border-t border-slate-100 pt-3 sm:grid-cols-2 lg:grid-cols-5"><Select ariaLabel="Lead source" value={draft.source} onChange={value=>update('source',value)}><option value="">All Sources</option>{(options.sources||[]).map(item=><option key={item}>{item}</option>)}</Select><Select ariaLabel="Skill" value={draft.primarySkillId} onChange={value=>update('primarySkillId',value)}><option value="">All Skills</option>{(options.skills||[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select ariaLabel="Stage" value={draft.stageId} onChange={value=>update('stageId',value)}><option value="">All Stages</option>{(options.stages||[]).filter(item=>!draft.pipelineId||String(item.pipelineId)===String(draft.pipelineId)).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select ariaLabel="Company / Client" value={draft.customerName} onChange={value=>update('customerName',value)}><option value="">All Companies / Clients</option>{(options.reportCustomers||[]).map(item=><option key={item.id} value={item.name}>{item.name}</option>)}</Select><button className={button} onClick={reset}><RotateCcw className="h-4 w-4"/>Reset Filters</button></div>}</section>
    <nav className="flex overflow-x-auto border-b border-slate-200 bg-white">{categories.map(([key,title])=><button className={`whitespace-nowrap border-b-2 px-4 py-3 text-[10px] font-bold ${category===key?'border-red-500 text-red-600':'border-transparent text-slate-600 hover:text-red-600'}`} key={key} onClick={()=>setCategory(key)}><BarChart3 className="mr-2 inline h-3.5 w-3.5"/>{title}</button>)}</nav>
    {(report.loading||optionsRequest.loading)&&!report.data?<div className={`${card} grid min-h-72 place-items-center text-sm font-semibold text-slate-500`}>Loading report data…</div>:report.error?<div className={`${card} grid min-h-72 place-items-center p-8 text-center`}><div><XCircle className="mx-auto h-8 w-8 text-red-500"/><p className="mt-3 text-sm font-bold">{report.error}</p><button className={`${button} mt-4`} onClick={()=>setFilters({...filters})}>Retry</button></div></div>:<>
      <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{kpis.map(item=><Kpi key={item[0]} title={item[0]} value={item[1]??0} previous={item[2]} change={item[3]} icon={item[4]} tone={item[5]}/>)}</div>
      <div className={`grid gap-2 lg:grid-cols-2 ${visibleSections.length>4?'xl:grid-cols-5':'xl:grid-cols-4'}`}>{visibleSections}</div>
      <div className="grid gap-2 lg:grid-cols-2 xl:grid-cols-4"><MiniTable title="Top Performing Employees" rows={data.byEmployee} columns={[["Employee","label"],["Leads","value"],["Won","won"],["Pipeline Value","amount",money]]}/>{category!=='activities'&&<MiniTable title="New Companies Added" rows={data.newCompaniesTable} columns={[["Company","companyName"],["Added By","addedBy"],["Date","createdAt",value=>value?new Date(value).toLocaleDateString('en-IN'):'—'],["Leads","leads"]]}/>}<MiniTable title="Leads Requiring Follow-up" rows={data.followUps} columns={[["Lead","leadName"],["Company","companyName"],["Owner","owner"],["Days","days"]]}/><MiniTable title="Overdue Activities" rows={data.overdueActivities} columns={[["Activity","activity"],["Lead","leadName"],["Owner","owner"],["Due Date","dueDate",value=>value?new Date(value).toLocaleDateString('en-IN'):'—']]}/></div>
    </>}
  </div>;
}
