import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {Edit3,Plus,Trash2,X} from 'lucide-react';
import {domainIndustriesApi} from '../../api/domainIndustriesApi.js';

const EMPTY={name:'',description:'',active:true,displayOrder:0};
export function DomainIndustryMasterPage(){
 const client=useQueryClient(),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[form,setForm]=useState(EMPTY),[error,setError]=useState('');
 const query=useQuery({queryKey:['domain-industry-master','all'],queryFn:()=>domainIndustriesApi.list(true)});
 const refresh=()=>client.invalidateQueries({queryKey:['domain-industry-master']});
 const save=useMutation({mutationFn:()=>editing?domainIndustriesApi.update(editing.id,form):domainIndustriesApi.create(form),onSuccess:()=>{refresh();setOpen(false);setEditing(null);setForm(EMPTY);},onError:(e)=>setError(e.response?.data?.message||'Unable to save Domain / Industry.')});
 const remove=useMutation({mutationFn:domainIndustriesApi.remove,onSuccess:refresh});
 const show=(item=null)=>{setEditing(item);setForm(item?{name:item.name,description:item.description||'',active:item.active,displayOrder:item.displayOrder}:EMPTY);setError('');setOpen(true);};
 return <section className="space-y-5 text-[#06134a]"><div className="flex justify-between gap-4"><div><Link to="/settings" className="text-sm font-black">‹ Settings</Link><h1 className="mt-3 text-3xl font-black">Domain / Industry Master</h1><p className="mt-1 text-sm font-semibold text-slate-500">Manage domains available for Fixed Cost Projects.</p></div><button onClick={()=>show()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-red-600 px-4 text-sm font-black text-white"><Plus className="h-4 w-4"/> Add Domain / Industry</button></div>
 <div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Name','Description','Status','Used By','Actions'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{(query.data||[]).map(item=><tr key={item.id}><td className="px-4 py-3 font-black">{item.name}</td><td className="px-4 py-3">{item.description||'-'}</td><td className="px-4 py-3"><span className={`rounded px-2 py-1 text-xs font-black ${item.active?'bg-emerald-50 text-emerald-700':'bg-slate-100'}`}>{item.active?'Active':'Inactive'}</span></td><td className="px-4 py-3">{item.usageCount} projects</td><td className="flex gap-2 px-4 py-3"><button onClick={()=>show(item)} className="grid h-8 w-8 place-items-center rounded border"><Edit3 className="h-4 w-4"/></button><button onClick={()=>remove.mutate(item.id)} className="grid h-8 w-8 place-items-center rounded border border-red-200 text-red-600"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div>
 {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#06134a]/60 p-4"><form onSubmit={(e)=>{e.preventDefault();if(!form.name.trim())return setError('Name is required.');save.mutate();}} className="w-full max-w-lg rounded-xl bg-white"><div className="flex justify-between border-b p-5"><h2 className="text-xl font-black">{editing?'Edit':'Add'} Domain / Industry</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="space-y-4 p-5">{error&&<p className="rounded bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<label className="block text-sm font-bold">Name *<input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} className="mt-2 h-11 w-full rounded-lg border px-3"/></label><label className="block text-sm font-bold">Description<textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} className="mt-2 min-h-24 w-full rounded-lg border p-3"/></label><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={form.active} onChange={(e)=>setForm({...form,active:e.target.checked})}/> Active</label></div><div className="flex justify-end gap-3 border-t p-4"><button type="button" onClick={()=>setOpen(false)} className="h-10 rounded-lg border px-5 font-black">Cancel</button><button className="h-10 rounded-lg bg-red-600 px-5 font-black text-white">Save</button></div></form></div>}</section>;
}
