import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Edit3, Plus, Trash2, X } from 'lucide-react';
import { expenseAccountsApi } from '../../api/expenseAccountsApi.js';

const EMPTY = { accountName: '', description: '', active: true, displayOrder: 0 };

export function ExpenseAccountMasterPage() {
  const queryClient = useQueryClient();
  const [editing, setEditing] = useState(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [form, setForm] = useState(EMPTY);
  const [error, setError] = useState('');
  const query = useQuery({ queryKey: ['expense-account-master', 'all'], queryFn: () => expenseAccountsApi.list(true) });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ['expense-account-master'] }); queryClient.invalidateQueries({ queryKey: ['expense-filters'] }); queryClient.invalidateQueries({ queryKey: ['expense-list-filters'] }); };
  const save = useMutation({ mutationFn: () => editing ? expenseAccountsApi.update(editing.id, form) : expenseAccountsApi.create(form), onSuccess: () => { refresh(); setEditing(null); setModalOpen(false); setForm(EMPTY); }, onError: (e) => setError(e.response?.data?.message || 'Unable to save Expense Account.') });
  const remove = useMutation({ mutationFn: expenseAccountsApi.remove, onSuccess: refresh });
  const open = (account = null) => { setEditing(account); setModalOpen(true); setForm(account ? { accountName: account.accountName, description: account.description || '', active: account.active, displayOrder: account.displayOrder || 0 } : { ...EMPTY }); setError(''); };
  return <section className="space-y-5 text-[#06134a]">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link to="/settings" className="text-sm font-black">‹ Settings</Link><h1 className="mt-3 text-3xl font-black">Expense Account Master</h1><p className="mt-1 text-sm font-semibold text-slate-500">Manage the accounts available when creating and editing expenses.</p></div><button onClick={() => open()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-red-600 px-4 text-sm font-black text-white"><Plus className="h-4 w-4" /> Add Expense Account</button></div>
    {query.isError && <p className="rounded-lg bg-red-50 p-4 font-bold text-red-700">Unable to load Expense Accounts.</p>}
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Account Name','Description','Status','Used By','Actions'].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{(query.data || []).map((account) => <tr key={account.id}><td className="px-4 py-3 font-black">{account.accountName}</td><td className="px-4 py-3 text-slate-600">{account.description || '-'}</td><td className="px-4 py-3"><span className={`rounded px-2 py-1 text-xs font-black ${account.active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{account.active ? 'Active' : 'Inactive'}</span></td><td className="px-4 py-3 font-bold">{account.usageCount} expenses</td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={() => open(account)} className="grid h-8 w-8 place-items-center rounded border"><Edit3 className="h-4 w-4" /></button><button onClick={() => remove.mutate(account.id)} title={account.usageCount ? 'Inactivate account' : 'Delete account'} className="grid h-8 w-8 place-items-center rounded border border-red-200 text-red-600"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div>
    {modalOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-[#06134a]/60 p-4"><form onSubmit={(e) => { e.preventDefault(); if (!form.accountName.trim()) return setError('Account Name is required.'); save.mutate(); }} className="w-full max-w-lg rounded-xl bg-white shadow-2xl"><div className="flex justify-between border-b p-5"><h2 className="text-xl font-black">{editing ? 'Edit' : 'Add'} Expense Account</h2><button type="button" onClick={() => { setEditing(null); setModalOpen(false); setForm(EMPTY); }}><X /></button></div><div className="space-y-4 p-5">{error && <p className="rounded bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<label className="block text-sm font-bold">Account Name *<input value={form.accountName} onChange={(e) => setForm({...form, accountName:e.target.value})} className="mt-2 h-11 w-full rounded-lg border px-3" /></label><label className="block text-sm font-bold">Description<textarea value={form.description} onChange={(e) => setForm({...form, description:e.target.value})} className="mt-2 min-h-24 w-full rounded-lg border p-3" /></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.active} onChange={(e) => setForm({...form, active:e.target.checked})} /> Active</label></div><div className="flex justify-end gap-3 border-t p-4"><button type="button" onClick={() => { setEditing(null); setModalOpen(false); setForm(EMPTY); }} className="h-10 rounded-lg border px-5 font-black">Cancel</button><button disabled={save.isPending} className="h-10 rounded-lg bg-red-600 px-5 font-black text-white">{save.isPending ? 'Saving...' : 'Save'}</button></div></form></div>}
  </section>;
}
