import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, KeyRound, PlugZap, Save, ShieldAlert } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ConfirmDialog } from '../../components/ConfirmDialog.jsx';
import { irpSettingsApi } from '../../api/irpSettingsApi.js';

const defaults={SANDBOX:{apiBaseUrl:'https://einvapisandbox.irp5.in/irp5',gstin:'',apiVersion:'1.0',clientId:'',clientSecret:'',apiUsername:'',apiPassword:''},PRODUCTION:{apiBaseUrl:'https://api.einvoice5.gst.gov.in/irp5',gstin:'',apiVersion:'1.0',clientId:'',clientSecret:'',apiUsername:'',apiPassword:''}};
const fields=[['apiBaseUrl','API Base URL','text'],['clientId','Client ID','text'],['clientSecret','Client Secret','password'],['apiUsername','API Username','text'],['apiPassword','API Password','password'],['gstin','GSTIN','text'],['apiVersion','API Version','text']];

export function IrpSettingsPage(){
 const qc=useQueryClient(); const [env,setEnv]=useState('SANDBOX'); const [form,setForm]=useState(defaults.SANDBOX); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [activate,setActivate]=useState(false);
 const query=useQuery({queryKey:['irp-settings'],queryFn:irpSettingsApi.list});
 const current=useMemo(()=>query.data?.find(x=>x.environment===env),[query.data,env]); const active=query.data?.find(x=>x.active);
 useEffect(()=>{setForm({...defaults[env],...(current||{}),clientId:'',clientSecret:'',apiUsername:'',apiPassword:''});setMessage('');setError('');},[env,current?.id,current?.updatedAt]);
 const done=(text)=>{qc.invalidateQueries({queryKey:['irp-settings']});setMessage(text);setError('');}; const fail=e=>{setError(e.response?.data?.message||e.message||'Operation failed.');setMessage('');};
 const save=useMutation({mutationFn:()=>irpSettingsApi.save(env,form),onSuccess:()=>done(`${env} configuration saved securely.`),onError:fail});
 const test=useMutation({mutationFn:()=>irpSettingsApi.test(env),onSuccess:()=>done('Connection successful. IRP authentication completed.'),onError:fail});
 const activateMutation=useMutation({mutationFn:()=>irpSettingsApi.activate(env),onSuccess:()=>{done(`${env} is now active for new IRP operations.`);setActivate(false);},onError:e=>{fail(e);setActivate(false);}});
 const configuredHint=(key)=>current?.[`${key}Configured`]?'Configured — leave blank to keep existing value':'';
 return <section className="space-y-6">
  <div><Link to="/settings" className="text-sm font-black text-[#06134a]">‹ Settings</Link><h1 className="mt-3 text-3xl font-black text-[#06134a]">IRN / E-Invoice Settings</h1><p className="mt-2 text-sm font-semibold text-slate-500">Secure EY IRP 5 credentials and choose the environment used for new e-invoice operations.</p></div>
  <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4"><div><p className="text-xs font-black uppercase text-blue-600">Active Environment</p><p className="mt-1 text-xl font-black text-[#06134a]">{active?.environment||'Not configured'}</p></div><ShieldAlert className="h-8 w-8 text-blue-600"/></div>
  <div className="flex gap-2">{['SANDBOX','PRODUCTION'].map(x=><button key={x} onClick={()=>setEnv(x)} className={`rounded-lg px-5 py-2.5 text-sm font-black ${env===x?'bg-red-600 text-white':'border bg-white text-[#06134a]'}`}>{x==='SANDBOX'?'Sandbox Configuration':'Production Configuration'}</button>)}</div>
  {message&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 font-bold text-emerald-700">{message}</div>}{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 font-bold text-red-700">{error}</div>}
  <article className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div className="flex items-center gap-3"><KeyRound className="text-red-600"/><div><h2 className="text-xl font-black">{env==='SANDBOX'?'Sandbox':'Production'} Configuration</h2><p className="text-sm text-slate-500">Provider: EY IRP 5</p></div></div><div className="flex gap-2"><span className={`rounded-full px-3 py-1 text-xs font-black ${current?.configured?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{current?.configured?'Configured':'Not Configured'}</span><span className={`rounded-full px-3 py-1 text-xs font-black ${current?.active?'bg-blue-50 text-blue-700':'bg-slate-100 text-slate-600'}`}>{current?.active?'Active':'Inactive'}</span></div></div>
   <div className="grid gap-4 p-5 md:grid-cols-2">{fields.map(([key,label,type])=><label key={key} className={key==='apiBaseUrl'?'md:col-span-2':''}><span className="mb-2 block text-xs font-black">{label} <b className="text-red-600">*</b></span><input type={type} autoComplete="new-password" value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={configuredHint(key)} className="h-11 w-full rounded-lg border border-slate-200 px-4 text-sm font-semibold outline-none focus:border-red-300"/>{configuredHint(key)&&<small className="mt-1 block text-slate-500">{configuredHint(key)}</small>}</label>)}</div>
   <div className="flex flex-wrap justify-end gap-3 border-t p-5"><button disabled={!current?.configured||test.isPending} onClick={()=>test.mutate()} className="inline-flex h-10 items-center gap-2 rounded-lg border px-4 font-black"><PlugZap className="h-4 w-4"/>{test.isPending?'Testing...':'Test Connection'}</button><button disabled={!current?.configured||current?.active} onClick={()=>setActivate(true)} className="h-10 rounded-lg border border-blue-200 px-4 font-black text-blue-700">Activate Environment</button><button disabled={save.isPending} onClick={()=>save.mutate()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-red-600 px-5 font-black text-white"><Save className="h-4 w-4"/>{save.isPending?'Saving...':'Save Configuration'}</button></div>
  </article>
  {current?.lastConnectionTest&&<div className="flex items-center gap-3 text-sm font-semibold text-slate-600"><CheckCircle2 className={current.lastConnectionStatus==='SUCCESS'?'text-emerald-600':'text-red-600'}/>Last connection test: {new Date(current.lastConnectionTest).toLocaleString('en-IN')} — {current.lastConnectionStatus}</div>}
  <ConfirmDialog open={activate} title={`Activate ${env==='PRODUCTION'?'Production':'Sandbox'} Environment?`} message={env==='PRODUCTION'?'Production generates real GST e-invoices. Please confirm that the GSTIN and API credentials are correct.':'New IRP operations will use the saved Sandbox configuration.'} confirmLabel="Confirm & Activate" loading={activateMutation.isPending} onCancel={()=>setActivate(false)} onConfirm={()=>activateMutation.mutate()}/>
 </section>;
}
